---
site_name: LAB-1451 Device xAPI, Room Customization and Deployment # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
site_description: LAB-1451 Device xAPI, Room Customization and Deployment # must be same as "site_name"
site_author: John Doe
copyright: Copyright &copy; 2024 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
    - content.tooltips
    - content.footnote.tooltips
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  # - with-pdf:
  #     cover_title: LAB-1451
  #     cover_subtitle: Device xAPI, Room Customization and Deployment
  #     cover_logo: template_assets/wx1Splash_new.gif
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home&nbsp<i class="fa-solid fa-house" style="color:#B197FC;"></i>: index.md
  - Lab&nbsp<i class="fa-solid fa-flask" style="color:#fdd649;"></i>:
      - Lab Overview: overview.md
      - Part 1&colon; Lab Setup: wx1_1451_part_1.md
      - Part 2&colon; - Accessing Device xAPI : wx1_1451_part_2.md
      - Part 3&colon; - Building a Customization using Macros: wx1_1451_part_3.md
      - Part 4&colon; - Deploying your Customization: wx1_1451_part_4.md
      - Conclusion: conclusion.md
  - Tools&nbsp<i class="fa-solid fa-gear"></i>: tools.md
  - Ask a Question&nbsp<i class="fa-solid fa-hand" style="color:#63E6BE;"></i>: slido-QA-iFrame.md
  - Cheat Sheet&nbsp<i class="fa-solid fa-screwdriver-wrench" style="color:#1eeb40;"></i>:
      - CheatSheet: cheatsheet.md
      - Challenge Answers: challengeAnswers.md
  - Resources&nbsp<i class="fa-solid fa-globe" style="color:#04C0FC;"></i>: 
      - Communities: communities.md
      - Developer Sites: devSites.md
  